# fly.toml app configuration file generated for weatherman-d-t-4-1719238839-server on 2024-06-24T14:21:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'weatherman-d-t-4-1719238839-server'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 4
